/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                '#4cd7f6',
        'on-primary':             '#003640',
        'primary-container':      '#06b6d4',
        'on-primary-container':   '#00424f',
        'primary-fixed':          '#acedff',
        'primary-fixed-dim':      '#4cd7f6',
        'on-primary-fixed':       '#001f26',
        'on-primary-fixed-variant':'#004e5c',
        'inverse-primary':        '#00687a',
        'secondary':              '#7bd0ff',
        'on-secondary':           '#00354a',
        'secondary-container':    '#00a6e0',
        'on-secondary-container': '#00374d',
        'secondary-fixed':        '#c4e7ff',
        'secondary-fixed-dim':    '#7bd0ff',
        'on-secondary-fixed':     '#001e2c',
        'on-secondary-fixed-variant':'#004c69',
        'tertiary':               '#4edea3',
        'on-tertiary':            '#003824',
        'tertiary-container':     '#1bbd85',
        'on-tertiary-container':  '#00452e',
        'tertiary-fixed':         '#6ffbbe',
        'tertiary-fixed-dim':     '#4edea3',
        'on-tertiary-fixed':      '#002113',
        'on-tertiary-fixed-variant':'#005236',
        'error':                  '#ffb4ab',
        'on-error':               '#690005',
        'error-container':        '#93000a',
        'on-error-container':     '#ffdad6',
        'background':             '#051424',
        'on-background':          '#d4e4fa',
        'surface':                '#051424',
        'surface-dim':            '#051424',
        'surface-bright':         '#2c3a4c',
        'surface-container-lowest':'#010f1f',
        'surface-container-low':  '#0d1c2d',
        'surface-container':      '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest':'#273647',
        'on-surface':             '#d4e4fa',
        'on-surface-variant':     '#bcc9cd',
        'surface-variant':        '#273647',
        'inverse-surface':        '#d4e4fa',
        'inverse-on-surface':     '#233143',
        'outline':                '#869397',
        'outline-variant':        '#3d494c',
        'surface-tint':           '#4cd7f6',
        // sentiment chart colors (raw hex for SHAP bars per stitch design)
        'up':                     '#10b981',
        'down-sentiment':         '#f43f5e',
        'flat-sentiment':         '#64748b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        xs:      '0.0625rem',
        sm:      '0.125rem',
        md:      '0.1875rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '0.75rem',
      },
      spacing: {
        'space-2xs':        '0.125rem',
        'space-xs':         '0.25rem',
        'space-sm':         '0.5rem',
        'space-md':         '0.75rem',
        'space-base':       '1rem',
        'space-lg':         '1.5rem',
        'space-xl':         '2rem',
        'space-2xl':        '3rem',
        'gutter-desktop':   '1rem',
        'gutter-compact':   '0.5rem',
        'panel-padding':    '1rem',
        'cell-padding-x':   '0.75rem',
        'cell-padding-y':   '0.375rem',
      },
      fontFamily: {
        'display-lg':     ['Inter', 'sans-serif'],
        'headline-lg':    ['Inter', 'sans-serif'],
        'headline-md':    ['Inter', 'sans-serif'],
        'headline-sm':    ['Inter', 'sans-serif'],
        'body-lg':        ['Inter', 'sans-serif'],
        'body-md':        ['Inter', 'sans-serif'],
        'body-sm':        ['Inter', 'sans-serif'],
        'label-caps':     ['Inter', 'sans-serif'],
        'code-lg':        ['JetBrains Mono', 'monospace'],
        'code-md':        ['JetBrains Mono', 'monospace'],
        'code-sm':        ['JetBrains Mono', 'monospace'],
        'label-mono':     ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['36px', { lineHeight:'44px', letterSpacing:'-0.025em', fontWeight:'600' }],
        'display-lg-mobile': ['28px', { lineHeight:'36px', letterSpacing:'-0.02em', fontWeight:'600' }],
        'headline-lg': ['24px', { lineHeight:'32px', letterSpacing:'-0.02em',  fontWeight:'600' }],
        'headline-md': ['20px', { lineHeight:'28px', letterSpacing:'-0.015em', fontWeight:'500' }],
        'headline-sm': ['16px', { lineHeight:'24px', letterSpacing:'-0.01em',  fontWeight:'500' }],
        'body-lg':     ['15px', { lineHeight:'24px', letterSpacing:'-0.005em', fontWeight:'400' }],
        'body-md':     ['13px', { lineHeight:'20px', letterSpacing:'0em',      fontWeight:'400' }],
        'body-sm':     ['12px', { lineHeight:'18px', letterSpacing:'0.005em',  fontWeight:'400' }],
        'code-lg':     ['18px', { lineHeight:'26px', letterSpacing:'-0.02em',  fontWeight:'500' }],
        'code-md':     ['13px', { lineHeight:'18px', letterSpacing:'-0.01em',  fontWeight:'400' }],
        'code-sm':     ['11px', { lineHeight:'16px', letterSpacing:'0em',      fontWeight:'400' }],
        'label-caps':  ['11px', { lineHeight:'16px', letterSpacing:'0.06em',   fontWeight:'600' }],
        'label-mono':  ['10px', { lineHeight:'14px', letterSpacing:'0.04em',   fontWeight:'500' }],
      },
      keyframes: {
        shimmer: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'progress-slide': {
          '0%':   { left: '-40%', width: '30%' },
          '50%':  { width: '60%' },
          '100%': { left: '110%', width: '30%' },
        },
      },
      animation: {
        shimmer:         'shimmer 2s infinite',
        'shimmer-slow':  'shimmer 2.4s infinite',
        'progress-slide':'progress-slide 1.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
